stages:
  - build
  - test

## Set environment variables for folders in "cache" job settings for npm modules and Cypress binary
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

## Install NPM dependencies and Cypress
install:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: build
  script:
    - npm ci

ui-chrome-tests:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm start &
    # run Cypress tests in parallel
    - npx cypress run